language: node_js

os:
  - linux
  # Temporarily disable OSX builds until newer Pandoc binary available
  #- osx

# Currently pandoc-citeproc is also necessary for Linux
addons:
  apt:
    packages:
      - pandoc-citeproc

node_js:
  - 8

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
