language: node_js
node_js:
  - '10'

os:
  - linux
  # Currently, don't run on OSX because using citeproc
  # - osx

cache:
  directories:
    - node_modules

before_install:
  # Install Pandoc from deb to get pandoc-citeproc as well
  - wget https://github.com/jgm/pandoc/releases/download/2.2.3.2/pandoc-2.2.3.2-1-amd64.deb
  - sudo dpkg -i pandoc-2.2.3.2-1-amd64.deb

script:
  - npm run lint
  - npm run cover
  - npm run docs

after_success:
  # Upload test coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # Deploy documentation to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: npx semantic-release
