language: node_js
node_js:
  - '10'

# Run on Linux and MacOS
os:
  - linux
  - osx

script:
  # Temporarily disable dependency checking
  # - npm run check
  - npm run lint
  # Force exit to prevent the hanging on Travis
  - npm run test:cover -- --forceExit
  - npm run docs
  - npm run build

after_success:
  # Upload test coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # Deploy documentation to Github Pages (only on Linux)
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux

  # Do a semantic release (only on Linux)
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
