language: node_js
node_js:
  - '10'

os:
  - linux
  - osx

script:
  - npm run lint
  - npm run cover
  - npm run docs
  - npm run build
  - npm run bundle:$TRAVIS_OS_NAME

after_success:
  # Upload test coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # Deploy documentation to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master
  
  # Do a semantic release but only on linux
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
      condition: "$TRAVIS_OS_NAME==linux"
