language: node_js

os:
  - linux
  - osx

node_js:
  - 8

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
