language: node_js

os:
  - linux
  - osx

node_js:
  - 8

cache:
  directories:
    - node_modules

before_script:
  # Get Pandoc and any other requirements
  - npm run setup

script:
  - npm run lint
  - npm run cover
  - npm run docs

after_success:
  # Upload test coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # Deploy documentation to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master
