language: node_js
node_js:
  - '10'

os:
  - linux
  # Currently, don't run on OSX because using citeproc
  # - osx

# Install code signing tool 
#addons:
  #apt:
  #  sources:
  #    - sourceline: ppa:likemartinma/osslsigncode
  #  packages:
  #    - osslsigncode

cache:
  directories:
    - node_modules
    - '$HOME/.npm'

before_install:
  # Decrypt code signing certificates (see https://docs.travis-ci.com/user/encrypting-files/)
  - openssl aes-256-cbc -K $encrypted_7e2bde0bdb09_key -iv $encrypted_7e2bde0bdb09_iv -in win-cert.p12.enc -out win-cert.p12 -d

# Install node_modules
install:
  - npm install

script:
  - npm run lint
  - npm run cover
  - npm run docs
#  - npm run build
#  - npm run bundle

after_success:
  # Upload test coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # Deploy documentation to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: npx semantic-release
