language: node_js

os:
  - linux
  - osx

node_js:
  - 8

cache:
  directories:
    - node_modules

before_install:
  # Install pandoc-citeproc by downloading the pandoc bundle 
  # (delete pandoc itself because we want to automatically download the version specified by this package)
  - curl -sL https://github.com/jgm/pandoc/releases/download/2.2.1/pandoc-2.2.1-linux.tar.gz | tar zx --strip-components=2
  - rm -rf pandoc

script:
  - npm run lint
  - npm run cover
  - npm run check
  - npm run docs

after_success:
  # Upload test coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # Deploy documentation to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master
