language: node_js

os:
  - linux
  # Temporarily disable OSX builds until newer Pandoc binary available
  #- osx

node_js:
  - 8

cache:
  directories:
    - node_modules

install:
  # Install pandoc-citeproc (delete pandoc because we want to automaticaaly download our version)
  - curl -sL https://github.com/jgm/pandoc/releases/download/2.1.1/pandoc-2.1.1-linux.tar.gz | tar zx --strip-components=2
  - rm -rf pandoc

script:
  - npm run lint
  - npm run cover

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Deploy documentation to Github Pages
# See https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master
